version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: portfolio_postgres
    environment:
      POSTGRES_USER: me
      PGUSER: me
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: portfolio
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio_network

  app:
    image: ramdhanistars/porto-api:latest
    container_name: portfolio_app
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgresql://me:123@postgres:5432/portfolio
      ADMIN_USER: admin
      ADMIN_PASS: admin
    depends_on:
      - postgres
    networks:
      - portfolio_network

  web:
    image: ramdhanistars/porto:latest
    container_name: portfolio_web
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      API_URL: http://app:3000
    depends_on:
      - app
    networks:
      - portfolio_network

volumes:
  postgres_data:

networks:
  portfolio_network:
    driver: bridge
